### PR TITLE
Feature/delete orders

### PR DESCRIPTION
**Pull request by OlaStalberg**

### CODE REVIEW

**Review by asgeirn — CHANGES_REQUESTED** [review]
This PR seems to include (some of) the modifications from #98 as well.

**Comment by asgeirn** [comment]
@OlaStalberg I have rebased and force-pushed the branch to clean away commits related to #98 

You should delete your local branch and checkout from origin again:

```
git checkout master
git fetch origin
git branch -D feature/delete-orders
git checkout feature/delete-orders
```

**Comment by OlaStalberg** [comment]
Done! @asgeirn

**Review by asgeirn — APPROVED** [review]
👍

**Pull request merged**
